services:
  postgres:
    image: postgres:16
    container_name: medical_db
    environment:
      POSTGRES_DB: medical_scheduling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4545:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical_scheduling"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: medical_api
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical_scheduling
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
